### ISSUE TITLE
Add expense 

### ISSUE THREAD

**Issue by randallnhr** [AY2223S2-CS2103T-W09-2/tp#2]
As a user, I am able to add an expense to the expense tracker.

- [ ] Add Expense Class #44 
- [ ] Modify Storage Class to parse expense #45 
- [ ] Modify Command Parser #51
