### ISSUE TITLE
Add category 

### ISSUE THREAD

**Issue by randallnhr** [AY2223S2-CS2103T-W09-2/tp#5]
As a user, I am able to add a new category of expense to the expense tracker.

- [ ] Add Category Class #30 
- [ ] Modify Storage Class to parse category #29
- [ ] Modify Command Parser #50
