### ISSUE TITLE
Delete a category

### ISSUE THREAD

**Issue by gitsac** [AY2223S2-CS2103T-W09-2/tp#6]
As a user, I am able to delete categories that I no longer need.

- [ ] Add Category Class #30 
- [ ] Modify Storage Class to parse category #29
- [ ] Modify Command Parser #50
